### ISSUE TITLE
Google tracking script is not loaded with default plugin preferencies. Other: missing language strings

### ISSUE THREAD

**Issue by Jimmi08** [lonalore/google_analytics#2]
Hi, Just let you know (fresh install, on live server). It seems like English_global.php is not loaded, but it is there.
![image](https://cloud.githubusercontent.com/assets/5429548/13428792/faf90820-dfbc-11e5-946e-1d29af7691a9.png)

![image](https://cloud.githubusercontent.com/assets/5429548/13428779/e86b6e5a-dfbc-11e5-978e-83b3bb1b5866.png)

And how I can check if does plugin works? (other way then to wait for GA)  Not see analytics.js or inline code in source code. Where to look? Thanks

**Comment by lonalore** [comment]
This should fix the second part of this issue. Suddenly I have no idea for the language issue. :/

**Comment by lonalore** [comment]
It's interesting, because "LAN_PLUGIN_GOOGLE_ANALYTICS_NAME" is defined in a global language file, and it should be available globally. Please try to refresh uploaded files, and clear cache.
